default:
    image: openjdk:11-jdk

stages:
    - build
    - test
    - deploy

test-job:
    stage: test
    script:
        - ./gradlew test
    artifacts:
        when: always
        reports:
            junit:
                - build/test-results/test/TEST-*.xml

build-job:
    stage: build
    script:
        - ./gradlew assemble
    artifacts:
        when: always
        paths:
            - build/libs/*.jar


deploy-job:
    stage: deploy
    script:
        - echo "Deploy"
